events { 
    worker_connections 1024;
}

http {
    #80 -> 443
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    #HTTPS server
    server {
        listen 443 ssl;
        server_name localhost;

        #SSL/TLS certificates
        ssl_certificate /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        #Cipher Suites
        ssl_protocols TLSv1.2 TLSv1.3; #no TLS 1.0
        ssl_prefer_server_ciphers on; #no ciphers without authentication
        ssl_ciphers HIGH:!aNULL:!MD5; #no MD5

        location / {
            #internal redirection to the FastAPI container
            proxy_pass http://backend:8000;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}